[program:multiplicationmaster]
command=/usr/bin/python3 main_fastapi.py
directory=/home/lee/code/multiplicationmaster
user=lee
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/multiplicationmaster/app.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile=/var/log/multiplicationmaster/error.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=5

[program:cloudflared-multiplicationmaster]
command=cloudflared tunnel --url localhost:8338 --name multiplicationmasterprod --protocol http2
directory=/home/lee
user=lee
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/cloudflared/multiplicationmaster.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile=/var/log/cloudflared/multiplicationmaster-error.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=5
